package com.changyi.fi.core.dao;

import com.changyi.fi.core.model.SysAccessPO;
import com.changyi.fi.core.model.SysServImplPO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCESS
     *
     * @mbggenerated
     */
    int insert(SysAccessPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCESS
     *
     * @mbggenerated
     */
    int insertSelective(SysAccessPO record);

    int updateSysServImpl(SysServImplPO servImplPO);

    public List<SysServImplPO> getSysServImplsByType(@Param("type") String type);

}