package com.changyi.fi.dao;

import com.changyi.fi.model.CustomerLoginPO;

public interface CustomerLoginPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_customer_login
     *
     * @mbggenerated
     */
    int insert(CustomerLoginPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_customer_login
     *
     * @mbggenerated
     */
    int insertSelective(CustomerLoginPO record);
}