package com.changyi.fi.dao;

import com.changyi.fi.model.CustomerPO;
import com.changyi.fi.model.CustomerPOExample;
import com.changyi.fi.model.VInvoicePO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CustomerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated
     */
    int insert(CustomerPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated
     */
    int insertSelective(CustomerPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated
     */
    int updateSelective(CustomerPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated
     */
    int update(CustomerPO record);

    @Select("select count(*) from CUSTOMER t where t.OPEN_ID = #{openId}")
    @Result(javaType = Long.class)
    public Long countCustomerById(@Param("openId") String openId);
}