package com.changyi.fi.dao;

import com.changyi.fi.model.CustomerPO;
import com.changyi.fi.model.CustomerPOExample;
import org.apache.ibatis.annotations.Param;

public interface CustomerPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated
     */
    int insert(CustomerPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated
     */
    int insertSelective(CustomerPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerPO record, @Param("example") CustomerPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerPO record, @Param("example") CustomerPOExample example);
}