package com.changyi.fi.dao;

import com.changyi.fi.model.EnterprisePO;
import com.changyi.fi.model.EnterprisePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnterprisePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_enterprise
     *
     * @mbggenerated
     */
    int insert(EnterprisePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_enterprise
     *
     * @mbggenerated
     */
    int insertSelective(EnterprisePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_enterprise
     *
     * @mbggenerated
     */
    List<EnterprisePO> selectByExampleWithBLOBs(EnterprisePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_enterprise
     *
     * @mbggenerated
     */
    List<EnterprisePO> selectByExample(EnterprisePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_enterprise
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EnterprisePO record, @Param("example") EnterprisePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_enterprise
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") EnterprisePO record, @Param("example") EnterprisePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_enterprise
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EnterprisePO record, @Param("example") EnterprisePOExample example);
}