package com.changyi.fi.dao;

import com.changyi.fi.model.InvoicePO;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface InvoicePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    int insert(InvoicePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    int insertSelective(InvoicePO record);
}