package com.changyi.fi.dao;

import com.changyi.fi.model.InvoicePO;
import com.changyi.fi.model.InvoicePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvoicePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_invoice
     *
     * @mbggenerated
     */
    int insert(InvoicePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_invoice
     *
     * @mbggenerated
     */
    int insertSelective(InvoicePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_invoice
     *
     * @mbggenerated
     */
    List<InvoicePO> selectByExample(InvoicePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_invoice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InvoicePO record, @Param("example") InvoicePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_invoice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InvoicePO record, @Param("example") InvoicePOExample example);
}