package com.changyi.fi.dao;

import com.changyi.fi.model.MerchantTypePO;

public interface MerchantTypePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_TYPE
     *
     * @mbggenerated
     */
    int insert(MerchantTypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_TYPE
     *
     * @mbggenerated
     */
    int insertSelective(MerchantTypePO record);
}