package com.changyi.fi.dao;

import com.changyi.fi.model.*;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OrderDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_order
     *
     * @mbggenerated
     */
    int insertOrder(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_order
     *
     * @mbggenerated
     */
    List<OrderPO> selectOrderByExample(OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_order
     *
     * @mbggenerated
     */
    int updateOrderByExampleSelective(@Param("record") OrderPO record, @Param("example") OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_attr_ins
     *
     * @mbggenerated
     */
    int deleteAttrInsByExample(ProdAttrInsPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_attr_ins
     *
     * @mbggenerated
     */
    int insertAttrIns(ProdAttrInsPO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_attr_ins
     *
     * @mbggenerated
     */
    List<ProdAttrInsPO> selectAttrInsByExample(ProdAttrInsPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_attr_ins
     *
     * @mbggenerated
     */
    int updateAttrInsByExampleSelective(@Param("record") ProdAttrInsPO record, @Param("example") ProdAttrInsPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_attr
     *
     * @mbggenerated
     */
    int deleteAttrByExample(ProdAttrPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_attr
     *
     * @mbggenerated
     */
    int insertAttr(ProdAttrPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_attr
     *
     * @mbggenerated
     */
    List<ProdAttrPO> selectAttrByExample(ProdAttrPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_attr
     *
     * @mbggenerated
     */
    int updateAttrByExampleSelective(@Param("record") ProdAttrPO record, @Param("example") ProdAttrPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_attr_ins
     *
     * @mbggenerated
     */
    int deleteProdTypeByExample(ProdTypePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_type
     *
     * @mbggenerated
     */
    int insertProdType(ProdTypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_type
     *
     * @mbggenerated
     */
    List<ProdTypePO> selectProdTypeByExample(ProdTypePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_type
     *
     * @mbggenerated
     */
    int updateProdTypeByExampleSelective(@Param("record") ProdTypePO record, @Param("example") ProdTypePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_attr_ins
     *
     * @mbggenerated
     */
    int deleteProductByExample(ProductPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_product
     *
     * @mbggenerated
     */
    int insertProduct(ProductPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_product
     *
     * @mbggenerated
     */
    List<ProductPO> selectProductByExample(ProductPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_product
     *
     * @mbggenerated
     */
    int updateProductByExampleSelective(@Param("record") ProductPO record, @Param("example") ProductPOExample example);


}