package com.changyi.fi.dao;

import com.changyi.fi.model.ProdTypePO;
import com.changyi.fi.model.ProdTypePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProdTypePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_type
     *
     * @mbggenerated
     */
    int insert(ProdTypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_type
     *
     * @mbggenerated
     */
    int insertSelective(ProdTypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_type
     *
     * @mbggenerated
     */
    List<ProdTypePO> selectByExample(ProdTypePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProdTypePO record, @Param("example") ProdTypePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_prod_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProdTypePO record, @Param("example") ProdTypePOExample example);
}