package com.changyi.fi.dao;

import com.changyi.fi.model.ProductPO;
import com.changyi.fi.model.ProductPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_product
     *
     * @mbggenerated
     */
    int insert(ProductPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_product
     *
     * @mbggenerated
     */
    int insertSelective(ProductPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_product
     *
     * @mbggenerated
     */
    List<ProductPO> selectByExample(ProductPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductPO record, @Param("example") ProductPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inc_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductPO record, @Param("example") ProductPOExample example);
}