package com.changyi.fi.dao;

import com.changyi.fi.model.SysAccessPO;
import com.changyi.fi.model.SysAccessPOExample;
import java.util.List;

public interface SysAccessPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access
     *
     * @mbggenerated
     */
    int insert(SysAccessPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access
     *
     * @mbggenerated
     */
    int insertSelective(SysAccessPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access
     *
     * @mbggenerated
     */
    List<SysAccessPO> selectByExample(SysAccessPOExample example);
}