package com.changyi.fi.dao;

import com.changyi.fi.model.VInvoicePO;
import com.changyi.fi.model.VInvoicePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VInvoicePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_invoice
     *
     * @mbggenerated
     */
    int insert(VInvoicePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_invoice
     *
     * @mbggenerated
     */
    int insertSelective(VInvoicePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_invoice
     *
     * @mbggenerated
     */
    List<VInvoicePO> selectByExample(VInvoicePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_invoice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VInvoicePO record, @Param("example") VInvoicePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_invoice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VInvoicePO record, @Param("example") VInvoicePOExample example);
}