package com.changyi.fi.core.model;

import java.util.Date;

public class SysOutboundPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_outbound.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_outbound.proxy_ip
     *
     * @mbggenerated
     */
    private String proxyIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_outbound.proxy_port
     *
     * @mbggenerated
     */
    private String proxyPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_outbound.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_outbound.protocol
     *
     * @mbggenerated
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_outbound.method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_outbound.domain
     *
     * @mbggenerated
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_outbound.port
     *
     * @mbggenerated
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_outbound.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_outbound.call_time
     *
     * @mbggenerated
     */
    private Date callTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_outbound.id
     *
     * @return the value of sys_outbound.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_outbound.id
     *
     * @param id the value for sys_outbound.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_outbound.proxy_ip
     *
     * @return the value of sys_outbound.proxy_ip
     *
     * @mbggenerated
     */
    public String getProxyIp() {
        return proxyIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_outbound.proxy_ip
     *
     * @param proxyIp the value for sys_outbound.proxy_ip
     *
     * @mbggenerated
     */
    public void setProxyIp(String proxyIp) {
        this.proxyIp = proxyIp == null ? null : proxyIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_outbound.proxy_port
     *
     * @return the value of sys_outbound.proxy_port
     *
     * @mbggenerated
     */
    public String getProxyPort() {
        return proxyPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_outbound.proxy_port
     *
     * @param proxyPort the value for sys_outbound.proxy_port
     *
     * @mbggenerated
     */
    public void setProxyPort(String proxyPort) {
        this.proxyPort = proxyPort == null ? null : proxyPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_outbound.account
     *
     * @return the value of sys_outbound.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_outbound.account
     *
     * @param account the value for sys_outbound.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_outbound.protocol
     *
     * @return the value of sys_outbound.protocol
     *
     * @mbggenerated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_outbound.protocol
     *
     * @param protocol the value for sys_outbound.protocol
     *
     * @mbggenerated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_outbound.method
     *
     * @return the value of sys_outbound.method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_outbound.method
     *
     * @param method the value for sys_outbound.method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_outbound.domain
     *
     * @return the value of sys_outbound.domain
     *
     * @mbggenerated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_outbound.domain
     *
     * @param domain the value for sys_outbound.domain
     *
     * @mbggenerated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_outbound.port
     *
     * @return the value of sys_outbound.port
     *
     * @mbggenerated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_outbound.port
     *
     * @param port the value for sys_outbound.port
     *
     * @mbggenerated
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_outbound.url
     *
     * @return the value of sys_outbound.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_outbound.url
     *
     * @param url the value for sys_outbound.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_outbound.call_time
     *
     * @return the value of sys_outbound.call_time
     *
     * @mbggenerated
     */
    public Date getCallTime() {
        return callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_outbound.call_time
     *
     * @param callTime the value for sys_outbound.call_time
     *
     * @mbggenerated
     */
    public void setCallTime(Date callTime) {
        this.callTime = callTime;
    }
}