package com.changyi.fi.model;

import java.util.Date;

public class EnterpriseHistoryPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise_modify_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise_modify_history.credit_code
     *
     * @mbggenerated
     */
    private String creditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise_modify_history.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise_modify_history.modify_by
     *
     * @mbggenerated
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise_modify_history.field
     *
     * @mbggenerated
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise_modify_history.old_value
     *
     * @mbggenerated
     */
    private String oldValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise_modify_history.new_value
     *
     * @mbggenerated
     */
    private String newValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise_modify_history.id
     *
     * @return the value of inc_enterprise_modify_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise_modify_history.id
     *
     * @param id the value for inc_enterprise_modify_history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise_modify_history.credit_code
     *
     * @return the value of inc_enterprise_modify_history.credit_code
     *
     * @mbggenerated
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise_modify_history.credit_code
     *
     * @param creditCode the value for inc_enterprise_modify_history.credit_code
     *
     * @mbggenerated
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise_modify_history.modify_time
     *
     * @return the value of inc_enterprise_modify_history.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise_modify_history.modify_time
     *
     * @param modifyTime the value for inc_enterprise_modify_history.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise_modify_history.modify_by
     *
     * @return the value of inc_enterprise_modify_history.modify_by
     *
     * @mbggenerated
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise_modify_history.modify_by
     *
     * @param modifyBy the value for inc_enterprise_modify_history.modify_by
     *
     * @mbggenerated
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy == null ? null : modifyBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise_modify_history.field
     *
     * @return the value of inc_enterprise_modify_history.field
     *
     * @mbggenerated
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise_modify_history.field
     *
     * @param field the value for inc_enterprise_modify_history.field
     *
     * @mbggenerated
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise_modify_history.old_value
     *
     * @return the value of inc_enterprise_modify_history.old_value
     *
     * @mbggenerated
     */
    public String getOldValue() {
        return oldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise_modify_history.old_value
     *
     * @param oldValue the value for inc_enterprise_modify_history.old_value
     *
     * @mbggenerated
     */
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue == null ? null : oldValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise_modify_history.new_value
     *
     * @return the value of inc_enterprise_modify_history.new_value
     *
     * @mbggenerated
     */
    public String getNewValue() {
        return newValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise_modify_history.new_value
     *
     * @param newValue the value for inc_enterprise_modify_history.new_value
     *
     * @mbggenerated
     */
    public void setNewValue(String newValue) {
        this.newValue = newValue == null ? null : newValue.trim();
    }
}