package com.changyi.fi.model;

import java.util.Date;

public class EnterpriseHistoryPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENTERPRISE_MODIFY_HISTORY.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENTERPRISE_MODIFY_HISTORY.ENT_CREDIT_CODE
     *
     * @mbggenerated
     */
    private String ENT_CREDIT_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENTERPRISE_MODIFY_HISTORY.CREDIT_CODE
     *
     * @mbggenerated
     */
    private String CREDIT_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENTERPRISE_MODIFY_HISTORY.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date MODIFY_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENTERPRISE_MODIFY_HISTORY.MODIFY_BY
     *
     * @mbggenerated
     */
    private String MODIFY_BY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENTERPRISE_MODIFY_HISTORY.FIELD
     *
     * @mbggenerated
     */
    private String FIELD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENTERPRISE_MODIFY_HISTORY.OLD_VALUE
     *
     * @mbggenerated
     */
    private String OLD_VALUE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENTERPRISE_MODIFY_HISTORY.NEW_VALUE
     *
     * @mbggenerated
     */
    private String NEW_VALUE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENTERPRISE_MODIFY_HISTORY.ID
     *
     * @return the value of ENTERPRISE_MODIFY_HISTORY.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENTERPRISE_MODIFY_HISTORY.ID
     *
     * @param ID the value for ENTERPRISE_MODIFY_HISTORY.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENTERPRISE_MODIFY_HISTORY.ENT_CREDIT_CODE
     *
     * @return the value of ENTERPRISE_MODIFY_HISTORY.ENT_CREDIT_CODE
     *
     * @mbggenerated
     */
    public String getENT_CREDIT_CODE() {
        return ENT_CREDIT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENTERPRISE_MODIFY_HISTORY.ENT_CREDIT_CODE
     *
     * @param ENT_CREDIT_CODE the value for ENTERPRISE_MODIFY_HISTORY.ENT_CREDIT_CODE
     *
     * @mbggenerated
     */
    public void setENT_CREDIT_CODE(String ENT_CREDIT_CODE) {
        this.ENT_CREDIT_CODE = ENT_CREDIT_CODE == null ? null : ENT_CREDIT_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENTERPRISE_MODIFY_HISTORY.CREDIT_CODE
     *
     * @return the value of ENTERPRISE_MODIFY_HISTORY.CREDIT_CODE
     *
     * @mbggenerated
     */
    public String getCREDIT_CODE() {
        return CREDIT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENTERPRISE_MODIFY_HISTORY.CREDIT_CODE
     *
     * @param CREDIT_CODE the value for ENTERPRISE_MODIFY_HISTORY.CREDIT_CODE
     *
     * @mbggenerated
     */
    public void setCREDIT_CODE(String CREDIT_CODE) {
        this.CREDIT_CODE = CREDIT_CODE == null ? null : CREDIT_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENTERPRISE_MODIFY_HISTORY.MODIFY_TIME
     *
     * @return the value of ENTERPRISE_MODIFY_HISTORY.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Date getMODIFY_TIME() {
        return MODIFY_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENTERPRISE_MODIFY_HISTORY.MODIFY_TIME
     *
     * @param MODIFY_TIME the value for ENTERPRISE_MODIFY_HISTORY.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setMODIFY_TIME(Date MODIFY_TIME) {
        this.MODIFY_TIME = MODIFY_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENTERPRISE_MODIFY_HISTORY.MODIFY_BY
     *
     * @return the value of ENTERPRISE_MODIFY_HISTORY.MODIFY_BY
     *
     * @mbggenerated
     */
    public String getMODIFY_BY() {
        return MODIFY_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENTERPRISE_MODIFY_HISTORY.MODIFY_BY
     *
     * @param MODIFY_BY the value for ENTERPRISE_MODIFY_HISTORY.MODIFY_BY
     *
     * @mbggenerated
     */
    public void setMODIFY_BY(String MODIFY_BY) {
        this.MODIFY_BY = MODIFY_BY == null ? null : MODIFY_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENTERPRISE_MODIFY_HISTORY.FIELD
     *
     * @return the value of ENTERPRISE_MODIFY_HISTORY.FIELD
     *
     * @mbggenerated
     */
    public String getFIELD() {
        return FIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENTERPRISE_MODIFY_HISTORY.FIELD
     *
     * @param FIELD the value for ENTERPRISE_MODIFY_HISTORY.FIELD
     *
     * @mbggenerated
     */
    public void setFIELD(String FIELD) {
        this.FIELD = FIELD == null ? null : FIELD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENTERPRISE_MODIFY_HISTORY.OLD_VALUE
     *
     * @return the value of ENTERPRISE_MODIFY_HISTORY.OLD_VALUE
     *
     * @mbggenerated
     */
    public String getOLD_VALUE() {
        return OLD_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENTERPRISE_MODIFY_HISTORY.OLD_VALUE
     *
     * @param OLD_VALUE the value for ENTERPRISE_MODIFY_HISTORY.OLD_VALUE
     *
     * @mbggenerated
     */
    public void setOLD_VALUE(String OLD_VALUE) {
        this.OLD_VALUE = OLD_VALUE == null ? null : OLD_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENTERPRISE_MODIFY_HISTORY.NEW_VALUE
     *
     * @return the value of ENTERPRISE_MODIFY_HISTORY.NEW_VALUE
     *
     * @mbggenerated
     */
    public String getNEW_VALUE() {
        return NEW_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENTERPRISE_MODIFY_HISTORY.NEW_VALUE
     *
     * @param NEW_VALUE the value for ENTERPRISE_MODIFY_HISTORY.NEW_VALUE
     *
     * @mbggenerated
     */
    public void setNEW_VALUE(String NEW_VALUE) {
        this.NEW_VALUE = NEW_VALUE == null ? null : NEW_VALUE.trim();
    }
}