package com.changyi.fi.model;

import org.apache.commons.lang.StringUtils;

import java.math.BigDecimal;
import java.util.Date;

public class EnterprisePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.credit_code
     *
     * @mbggenerated
     */
    private String creditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.legal_person
     *
     * @mbggenerated
     */
    private String legalPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.reg_capital
     *
     * @mbggenerated
     */
    private BigDecimal regCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.establish_date
     *
     * @mbggenerated
     */
    private Date establishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.biz_period_start
     *
     * @mbggenerated
     */
    private Date bizPeriodStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.biz_period_end
     *
     * @mbggenerated
     */
    private Date bizPeriodEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.reg_authority
     *
     * @mbggenerated
     */
    private String regAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.bank
     *
     * @mbggenerated
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.bank_acct
     *
     * @mbggenerated
     */
    private String bankAcct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.modify_by
     *
     * @mbggenerated
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.biz_reg_num
     *
     * @mbggenerated
     */
    private String bizRegNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.org_code
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.taxpayer_code
     *
     * @mbggenerated
     */
    private String taxpayerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.industry
     *
     * @mbggenerated
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.source_url
     *
     * @mbggenerated
     */
    private String sourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_enterprise.main_biz
     *
     * @mbggenerated
     */
    private byte[] mainBiz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.credit_code
     *
     * @return the value of inc_enterprise.credit_code
     *
     * @mbggenerated
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.credit_code
     *
     * @param creditCode the value for inc_enterprise.credit_code
     *
     * @mbggenerated
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = handleValue(creditCode);

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.name
     *
     * @return the value of inc_enterprise.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.name
     *
     * @param name the value for inc_enterprise.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = handleValue(name);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.type
     *
     * @return the value of inc_enterprise.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.type
     *
     * @param type the value for inc_enterprise.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = handleValue(type);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.legal_person
     *
     * @return the value of inc_enterprise.legal_person
     *
     * @mbggenerated
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.legal_person
     *
     * @param legalPerson the value for inc_enterprise.legal_person
     *
     * @mbggenerated
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = handleValue(legalPerson);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.reg_capital
     *
     * @return the value of inc_enterprise.reg_capital
     *
     * @mbggenerated
     */
    public BigDecimal getRegCapital() {
        return regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.reg_capital
     *
     * @param regCapital the value for inc_enterprise.reg_capital
     *
     * @mbggenerated
     */
    public void setRegCapital(BigDecimal regCapital) {
        this.regCapital = regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.establish_date
     *
     * @return the value of inc_enterprise.establish_date
     *
     * @mbggenerated
     */
    public Date getEstablishDate() {
        return establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.establish_date
     *
     * @param establishDate the value for inc_enterprise.establish_date
     *
     * @mbggenerated
     */
    public void setEstablishDate(Date establishDate) {
        this.establishDate = establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.biz_period_start
     *
     * @return the value of inc_enterprise.biz_period_start
     *
     * @mbggenerated
     */
    public Date getBizPeriodStart() {
        return bizPeriodStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.biz_period_start
     *
     * @param bizPeriodStart the value for inc_enterprise.biz_period_start
     *
     * @mbggenerated
     */
    public void setBizPeriodStart(Date bizPeriodStart) {
        this.bizPeriodStart = bizPeriodStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.biz_period_end
     *
     * @return the value of inc_enterprise.biz_period_end
     *
     * @mbggenerated
     */
    public Date getBizPeriodEnd() {
        return bizPeriodEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.biz_period_end
     *
     * @param bizPeriodEnd the value for inc_enterprise.biz_period_end
     *
     * @mbggenerated
     */
    public void setBizPeriodEnd(Date bizPeriodEnd) {
        this.bizPeriodEnd = bizPeriodEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.reg_authority
     *
     * @return the value of inc_enterprise.reg_authority
     *
     * @mbggenerated
     */
    public String getRegAuthority() {
        return regAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.reg_authority
     *
     * @param regAuthority the value for inc_enterprise.reg_authority
     *
     * @mbggenerated
     */
    public void setRegAuthority(String regAuthority) {
        this.regAuthority = handleValue(regAuthority);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.address
     *
     * @return the value of inc_enterprise.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.address
     *
     * @param address the value for inc_enterprise.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = handleValue(address);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.phone
     *
     * @return the value of inc_enterprise.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.phone
     *
     * @param phone the value for inc_enterprise.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = handleValue(phone);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.bank
     *
     * @return the value of inc_enterprise.bank
     *
     * @mbggenerated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.bank
     *
     * @param bank the value for inc_enterprise.bank
     *
     * @mbggenerated
     */
    public void setBank(String bank) {
        this.bank = handleValue(bank);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.bank_acct
     *
     * @return the value of inc_enterprise.bank_acct
     *
     * @mbggenerated
     */
    public String getBankAcct() {
        return bankAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.bank_acct
     *
     * @param bankAcct the value for inc_enterprise.bank_acct
     *
     * @mbggenerated
     */
    public void setBankAcct(String bankAcct) {
        this.bankAcct = handleValue(bankAcct);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.create_time
     *
     * @return the value of inc_enterprise.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.create_time
     *
     * @param createTime the value for inc_enterprise.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.create_by
     *
     * @return the value of inc_enterprise.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.create_by
     *
     * @param createBy the value for inc_enterprise.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.modify_time
     *
     * @return the value of inc_enterprise.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.modify_time
     *
     * @param modifyTime the value for inc_enterprise.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.modify_by
     *
     * @return the value of inc_enterprise.modify_by
     *
     * @mbggenerated
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.modify_by
     *
     * @param modifyBy the value for inc_enterprise.modify_by
     *
     * @mbggenerated
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy == null ? null : modifyBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.biz_reg_num
     *
     * @return the value of inc_enterprise.biz_reg_num
     *
     * @mbggenerated
     */
    public String getBizRegNum() {
        return bizRegNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.biz_reg_num
     *
     * @param bizRegNum the value for inc_enterprise.biz_reg_num
     *
     * @mbggenerated
     */
    public void setBizRegNum(String bizRegNum) {
        this.bizRegNum = handleValue(bizRegNum);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.org_code
     *
     * @return the value of inc_enterprise.org_code
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.org_code
     *
     * @param orgCode the value for inc_enterprise.org_code
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = handleValue(orgCode);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.taxpayer_code
     *
     * @return the value of inc_enterprise.taxpayer_code
     *
     * @mbggenerated
     */
    public String getTaxpayerCode() {
        return taxpayerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.taxpayer_code
     *
     * @param taxpayerCode the value for inc_enterprise.taxpayer_code
     *
     * @mbggenerated
     */
    public void setTaxpayerCode(String taxpayerCode) {
        this.taxpayerCode = handleValue(taxpayerCode);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.industry
     *
     * @return the value of inc_enterprise.industry
     *
     * @mbggenerated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.industry
     *
     * @param industry the value for inc_enterprise.industry
     *
     * @mbggenerated
     */
    public void setIndustry(String industry) {
        this.industry = handleValue(industry);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.area
     *
     * @return the value of inc_enterprise.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.area
     *
     * @param area the value for inc_enterprise.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = handleValue(area);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.source_url
     *
     * @return the value of inc_enterprise.source_url
     *
     * @mbggenerated
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.source_url
     *
     * @param sourceUrl the value for inc_enterprise.source_url
     *
     * @mbggenerated
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = handleValue(sourceUrl);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_enterprise.main_biz
     *
     * @return the value of inc_enterprise.main_biz
     *
     * @mbggenerated
     */
    public byte[] getMainBiz() {
        return mainBiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_enterprise.main_biz
     *
     * @param mainBiz the value for inc_enterprise.main_biz
     *
     * @mbggenerated
     */
    public void setMainBiz(byte[] mainBiz) {
        this.mainBiz = mainBiz;
    }

    private String handleValue(String value) {
        String result = value == null ? null : value.trim();
        if (StringUtils.isBlank(value)) {
            return null;
        } else {
            return result;
        }
    }
}