package com.changyi.fi.model;

import java.util.Date;

public class InvoicePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.ENT_CREDIT_CODE
     *
     * @mbggenerated
     */
    private String ENT_CREDIT_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.OPEN_ID
     *
     * @mbggenerated
     */
    private String OPEN_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.TYPE
     *
     * @mbggenerated
     */
    private Short TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.USER_NAME
     *
     * @mbggenerated
     */
    private String USER_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.CREDIT_CODE
     *
     * @mbggenerated
     */
    private String CREDIT_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date CREATE_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date MODIFY_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.IS_DEFAULT
     *
     * @mbggenerated
     */
    private Short IS_DEFAULT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.ID
     *
     * @return the value of INVOICE.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.ID
     *
     * @param ID the value for INVOICE.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.ENT_CREDIT_CODE
     *
     * @return the value of INVOICE.ENT_CREDIT_CODE
     *
     * @mbggenerated
     */
    public String getENT_CREDIT_CODE() {
        return ENT_CREDIT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.ENT_CREDIT_CODE
     *
     * @param ENT_CREDIT_CODE the value for INVOICE.ENT_CREDIT_CODE
     *
     * @mbggenerated
     */
    public void setENT_CREDIT_CODE(String ENT_CREDIT_CODE) {
        this.ENT_CREDIT_CODE = ENT_CREDIT_CODE == null ? null : ENT_CREDIT_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.OPEN_ID
     *
     * @return the value of INVOICE.OPEN_ID
     *
     * @mbggenerated
     */
    public String getOPEN_ID() {
        return OPEN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.OPEN_ID
     *
     * @param OPEN_ID the value for INVOICE.OPEN_ID
     *
     * @mbggenerated
     */
    public void setOPEN_ID(String OPEN_ID) {
        this.OPEN_ID = OPEN_ID == null ? null : OPEN_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.TYPE
     *
     * @return the value of INVOICE.TYPE
     *
     * @mbggenerated
     */
    public Short getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.TYPE
     *
     * @param TYPE the value for INVOICE.TYPE
     *
     * @mbggenerated
     */
    public void setTYPE(Short TYPE) {
        this.TYPE = TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.USER_NAME
     *
     * @return the value of INVOICE.USER_NAME
     *
     * @mbggenerated
     */
    public String getUSER_NAME() {
        return USER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.USER_NAME
     *
     * @param USER_NAME the value for INVOICE.USER_NAME
     *
     * @mbggenerated
     */
    public void setUSER_NAME(String USER_NAME) {
        this.USER_NAME = USER_NAME == null ? null : USER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.CREDIT_CODE
     *
     * @return the value of INVOICE.CREDIT_CODE
     *
     * @mbggenerated
     */
    public String getCREDIT_CODE() {
        return CREDIT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.CREDIT_CODE
     *
     * @param CREDIT_CODE the value for INVOICE.CREDIT_CODE
     *
     * @mbggenerated
     */
    public void setCREDIT_CODE(String CREDIT_CODE) {
        this.CREDIT_CODE = CREDIT_CODE == null ? null : CREDIT_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.CREATE_TIME
     *
     * @return the value of INVOICE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.CREATE_TIME
     *
     * @param CREATE_TIME the value for INVOICE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.MODIFY_TIME
     *
     * @return the value of INVOICE.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Date getMODIFY_TIME() {
        return MODIFY_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.MODIFY_TIME
     *
     * @param MODIFY_TIME the value for INVOICE.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setMODIFY_TIME(Date MODIFY_TIME) {
        this.MODIFY_TIME = MODIFY_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.IS_DEFAULT
     *
     * @return the value of INVOICE.IS_DEFAULT
     *
     * @mbggenerated
     */
    public Short getIS_DEFAULT() {
        return IS_DEFAULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.IS_DEFAULT
     *
     * @param IS_DEFAULT the value for INVOICE.IS_DEFAULT
     *
     * @mbggenerated
     */
    public void setIS_DEFAULT(Short IS_DEFAULT) {
        this.IS_DEFAULT = IS_DEFAULT;
    }
}