package com.changyi.fi.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InvoicePOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public InvoicePOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(Integer value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(Integer value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(Integer value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<Integer> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODEIsNull() {
            addCriterion("ENT_CREDIT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODEIsNotNull() {
            addCriterion("ENT_CREDIT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODEEqualTo(String value) {
            addCriterion("ENT_CREDIT_CODE =", value, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODENotEqualTo(String value) {
            addCriterion("ENT_CREDIT_CODE <>", value, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODEGreaterThan(String value) {
            addCriterion("ENT_CREDIT_CODE >", value, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("ENT_CREDIT_CODE >=", value, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODELessThan(String value) {
            addCriterion("ENT_CREDIT_CODE <", value, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODELessThanOrEqualTo(String value) {
            addCriterion("ENT_CREDIT_CODE <=", value, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODELike(String value) {
            addCriterion("ENT_CREDIT_CODE like", value, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODENotLike(String value) {
            addCriterion("ENT_CREDIT_CODE not like", value, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODEIn(List<String> values) {
            addCriterion("ENT_CREDIT_CODE in", values, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODENotIn(List<String> values) {
            addCriterion("ENT_CREDIT_CODE not in", values, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODEBetween(String value1, String value2) {
            addCriterion("ENT_CREDIT_CODE between", value1, value2, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andENT_CREDIT_CODENotBetween(String value1, String value2) {
            addCriterion("ENT_CREDIT_CODE not between", value1, value2, "ENT_CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDIsNull() {
            addCriterion("OPEN_ID is null");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDIsNotNull() {
            addCriterion("OPEN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDEqualTo(String value) {
            addCriterion("OPEN_ID =", value, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDNotEqualTo(String value) {
            addCriterion("OPEN_ID <>", value, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDGreaterThan(String value) {
            addCriterion("OPEN_ID >", value, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDGreaterThanOrEqualTo(String value) {
            addCriterion("OPEN_ID >=", value, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDLessThan(String value) {
            addCriterion("OPEN_ID <", value, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDLessThanOrEqualTo(String value) {
            addCriterion("OPEN_ID <=", value, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDLike(String value) {
            addCriterion("OPEN_ID like", value, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDNotLike(String value) {
            addCriterion("OPEN_ID not like", value, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDIn(List<String> values) {
            addCriterion("OPEN_ID in", values, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDNotIn(List<String> values) {
            addCriterion("OPEN_ID not in", values, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDBetween(String value1, String value2) {
            addCriterion("OPEN_ID between", value1, value2, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andOPEN_IDNotBetween(String value1, String value2) {
            addCriterion("OPEN_ID not between", value1, value2, "OPEN_ID");
            return (Criteria) this;
        }

        public Criteria andTYPEIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTYPEIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTYPEEqualTo(Short value) {
            addCriterion("TYPE =", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotEqualTo(Short value) {
            addCriterion("TYPE <>", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEGreaterThan(Short value) {
            addCriterion("TYPE >", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEGreaterThanOrEqualTo(Short value) {
            addCriterion("TYPE >=", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPELessThan(Short value) {
            addCriterion("TYPE <", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPELessThanOrEqualTo(Short value) {
            addCriterion("TYPE <=", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEIn(List<Short> values) {
            addCriterion("TYPE in", values, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotIn(List<Short> values) {
            addCriterion("TYPE not in", values, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEBetween(Short value1, Short value2) {
            addCriterion("TYPE between", value1, value2, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotBetween(Short value1, Short value2) {
            addCriterion("TYPE not between", value1, value2, "TYPE");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMEIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMEIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMEEqualTo(String value) {
            addCriterion("USER_NAME =", value, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMENotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMEGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMELessThan(String value) {
            addCriterion("USER_NAME <", value, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMELessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMELike(String value) {
            addCriterion("USER_NAME like", value, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMENotLike(String value) {
            addCriterion("USER_NAME not like", value, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMEIn(List<String> values) {
            addCriterion("USER_NAME in", values, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMENotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMEBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andUSER_NAMENotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "USER_NAME");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODEIsNull() {
            addCriterion("CREDIT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODEIsNotNull() {
            addCriterion("CREDIT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODEEqualTo(String value) {
            addCriterion("CREDIT_CODE =", value, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODENotEqualTo(String value) {
            addCriterion("CREDIT_CODE <>", value, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODEGreaterThan(String value) {
            addCriterion("CREDIT_CODE >", value, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("CREDIT_CODE >=", value, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODELessThan(String value) {
            addCriterion("CREDIT_CODE <", value, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODELessThanOrEqualTo(String value) {
            addCriterion("CREDIT_CODE <=", value, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODELike(String value) {
            addCriterion("CREDIT_CODE like", value, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODENotLike(String value) {
            addCriterion("CREDIT_CODE not like", value, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODEIn(List<String> values) {
            addCriterion("CREDIT_CODE in", values, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODENotIn(List<String> values) {
            addCriterion("CREDIT_CODE not in", values, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODEBetween(String value1, String value2) {
            addCriterion("CREDIT_CODE between", value1, value2, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREDIT_CODENotBetween(String value1, String value2) {
            addCriterion("CREDIT_CODE not between", value1, value2, "CREDIT_CODE");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMEIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMEIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMEEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "MODIFY_TIME");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMENotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "MODIFY_TIME");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMEGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "MODIFY_TIME");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "MODIFY_TIME");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMELessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "MODIFY_TIME");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMELessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "MODIFY_TIME");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMEIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "MODIFY_TIME");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMENotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "MODIFY_TIME");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMEBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "MODIFY_TIME");
            return (Criteria) this;
        }

        public Criteria andMODIFY_TIMENotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "MODIFY_TIME");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTIsNull() {
            addCriterion("IS_DEFAULT is null");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTIsNotNull() {
            addCriterion("IS_DEFAULT is not null");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTEqualTo(Short value) {
            addCriterion("IS_DEFAULT =", value, "IS_DEFAULT");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTNotEqualTo(Short value) {
            addCriterion("IS_DEFAULT <>", value, "IS_DEFAULT");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTGreaterThan(Short value) {
            addCriterion("IS_DEFAULT >", value, "IS_DEFAULT");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_DEFAULT >=", value, "IS_DEFAULT");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTLessThan(Short value) {
            addCriterion("IS_DEFAULT <", value, "IS_DEFAULT");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTLessThanOrEqualTo(Short value) {
            addCriterion("IS_DEFAULT <=", value, "IS_DEFAULT");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTIn(List<Short> values) {
            addCriterion("IS_DEFAULT in", values, "IS_DEFAULT");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTNotIn(List<Short> values) {
            addCriterion("IS_DEFAULT not in", values, "IS_DEFAULT");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTBetween(Short value1, Short value2) {
            addCriterion("IS_DEFAULT between", value1, value2, "IS_DEFAULT");
            return (Criteria) this;
        }

        public Criteria andIS_DEFAULTNotBetween(Short value1, Short value2) {
            addCriterion("IS_DEFAULT not between", value1, value2, "IS_DEFAULT");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INVOICE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INVOICE
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}