package com.changyi.fi.model;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantInvoicePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.INV_ID
     *
     * @mbggenerated
     */
    private Integer INV_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.MER_ID
     *
     * @mbggenerated
     */
    private Integer MER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.MERCHANT_ID
     *
     * @mbggenerated
     */
    private Integer MERCHANT_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.INVOICE_ID
     *
     * @mbggenerated
     */
    private Integer INVOICE_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal AMOUNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date CREATE_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.ID
     *
     * @return the value of MERCHANT_INVOICE.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.ID
     *
     * @param ID the value for MERCHANT_INVOICE.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.INV_ID
     *
     * @return the value of MERCHANT_INVOICE.INV_ID
     *
     * @mbggenerated
     */
    public Integer getINV_ID() {
        return INV_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.INV_ID
     *
     * @param INV_ID the value for MERCHANT_INVOICE.INV_ID
     *
     * @mbggenerated
     */
    public void setINV_ID(Integer INV_ID) {
        this.INV_ID = INV_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.MER_ID
     *
     * @return the value of MERCHANT_INVOICE.MER_ID
     *
     * @mbggenerated
     */
    public Integer getMER_ID() {
        return MER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.MER_ID
     *
     * @param MER_ID the value for MERCHANT_INVOICE.MER_ID
     *
     * @mbggenerated
     */
    public void setMER_ID(Integer MER_ID) {
        this.MER_ID = MER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.MERCHANT_ID
     *
     * @return the value of MERCHANT_INVOICE.MERCHANT_ID
     *
     * @mbggenerated
     */
    public Integer getMERCHANT_ID() {
        return MERCHANT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.MERCHANT_ID
     *
     * @param MERCHANT_ID the value for MERCHANT_INVOICE.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMERCHANT_ID(Integer MERCHANT_ID) {
        this.MERCHANT_ID = MERCHANT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.INVOICE_ID
     *
     * @return the value of MERCHANT_INVOICE.INVOICE_ID
     *
     * @mbggenerated
     */
    public Integer getINVOICE_ID() {
        return INVOICE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.INVOICE_ID
     *
     * @param INVOICE_ID the value for MERCHANT_INVOICE.INVOICE_ID
     *
     * @mbggenerated
     */
    public void setINVOICE_ID(Integer INVOICE_ID) {
        this.INVOICE_ID = INVOICE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.AMOUNT
     *
     * @return the value of MERCHANT_INVOICE.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.AMOUNT
     *
     * @param AMOUNT the value for MERCHANT_INVOICE.AMOUNT
     *
     * @mbggenerated
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.CREATE_TIME
     *
     * @return the value of MERCHANT_INVOICE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.CREATE_TIME
     *
     * @param CREATE_TIME the value for MERCHANT_INVOICE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }
}