package com.changyi.fi.model;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.phone1
     *
     * @mbggenerated
     */
    private String phone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.phone2
     *
     * @mbggenerated
     */
    private String phone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.letitude
     *
     * @mbggenerated
     */
    private BigDecimal letitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.zip_code
     *
     * @mbggenerated
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.modify_by
     *
     * @mbggenerated
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.expire_time
     *
     * @mbggenerated
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.channel_id
     *
     * @mbggenerated
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inc_merchant.do_validate
     *
     * @mbggenerated
     */
    private Short doValidate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.id
     *
     * @return the value of inc_merchant.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.id
     *
     * @param id the value for inc_merchant.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.name
     *
     * @return the value of inc_merchant.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.name
     *
     * @param name the value for inc_merchant.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.type
     *
     * @return the value of inc_merchant.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.type
     *
     * @param type the value for inc_merchant.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.address
     *
     * @return the value of inc_merchant.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.address
     *
     * @param address the value for inc_merchant.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.email
     *
     * @return the value of inc_merchant.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.email
     *
     * @param email the value for inc_merchant.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.phone1
     *
     * @return the value of inc_merchant.phone1
     *
     * @mbggenerated
     */
    public String getPhone1() {
        return phone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.phone1
     *
     * @param phone1 the value for inc_merchant.phone1
     *
     * @mbggenerated
     */
    public void setPhone1(String phone1) {
        this.phone1 = phone1 == null ? null : phone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.phone2
     *
     * @return the value of inc_merchant.phone2
     *
     * @mbggenerated
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.phone2
     *
     * @param phone2 the value for inc_merchant.phone2
     *
     * @mbggenerated
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2 == null ? null : phone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.longitude
     *
     * @return the value of inc_merchant.longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.longitude
     *
     * @param longitude the value for inc_merchant.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.letitude
     *
     * @return the value of inc_merchant.letitude
     *
     * @mbggenerated
     */
    public BigDecimal getLetitude() {
        return letitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.letitude
     *
     * @param letitude the value for inc_merchant.letitude
     *
     * @mbggenerated
     */
    public void setLetitude(BigDecimal letitude) {
        this.letitude = letitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.zip_code
     *
     * @return the value of inc_merchant.zip_code
     *
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.zip_code
     *
     * @param zipCode the value for inc_merchant.zip_code
     *
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.status
     *
     * @return the value of inc_merchant.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.status
     *
     * @param status the value for inc_merchant.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.create_time
     *
     * @return the value of inc_merchant.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.create_time
     *
     * @param createTime the value for inc_merchant.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.create_by
     *
     * @return the value of inc_merchant.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.create_by
     *
     * @param createBy the value for inc_merchant.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.modify_time
     *
     * @return the value of inc_merchant.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.modify_time
     *
     * @param modifyTime the value for inc_merchant.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.modify_by
     *
     * @return the value of inc_merchant.modify_by
     *
     * @mbggenerated
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.modify_by
     *
     * @param modifyBy the value for inc_merchant.modify_by
     *
     * @mbggenerated
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy == null ? null : modifyBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.expire_time
     *
     * @return the value of inc_merchant.expire_time
     *
     * @mbggenerated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.expire_time
     *
     * @param expireTime the value for inc_merchant.expire_time
     *
     * @mbggenerated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.channel_id
     *
     * @return the value of inc_merchant.channel_id
     *
     * @mbggenerated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.channel_id
     *
     * @param channelId the value for inc_merchant.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inc_merchant.do_validate
     *
     * @return the value of inc_merchant.do_validate
     *
     * @mbggenerated
     */
    public Short getDoValidate() {
        return doValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inc_merchant.do_validate
     *
     * @param doValidate the value for inc_merchant.do_validate
     *
     * @mbggenerated
     */
    public void setDoValidate(Short doValidate) {
        this.doValidate = doValidate;
    }
}