package com.changyi.fi.model;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantInvoicePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.INV_ID
     *
     * @mbggenerated
     */
    private Integer invId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.MER_ID
     *
     * @mbggenerated
     */
    private Integer merId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.MERCHANT_ID
     *
     * @mbggenerated
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.INVOICE_ID
     *
     * @mbggenerated
     */
    private Integer invoiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT_INVOICE.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.ID
     *
     * @return the value of MERCHANT_INVOICE.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.ID
     *
     * @param id the value for MERCHANT_INVOICE.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.INV_ID
     *
     * @return the value of MERCHANT_INVOICE.INV_ID
     *
     * @mbggenerated
     */
    public Integer getInvId() {
        return invId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.INV_ID
     *
     * @param invId the value for MERCHANT_INVOICE.INV_ID
     *
     * @mbggenerated
     */
    public void setInvId(Integer invId) {
        this.invId = invId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.MER_ID
     *
     * @return the value of MERCHANT_INVOICE.MER_ID
     *
     * @mbggenerated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.MER_ID
     *
     * @param merId the value for MERCHANT_INVOICE.MER_ID
     *
     * @mbggenerated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.MERCHANT_ID
     *
     * @return the value of MERCHANT_INVOICE.MERCHANT_ID
     *
     * @mbggenerated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.MERCHANT_ID
     *
     * @param merchantId the value for MERCHANT_INVOICE.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.INVOICE_ID
     *
     * @return the value of MERCHANT_INVOICE.INVOICE_ID
     *
     * @mbggenerated
     */
    public Integer getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.INVOICE_ID
     *
     * @param invoiceId the value for MERCHANT_INVOICE.INVOICE_ID
     *
     * @mbggenerated
     */
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.AMOUNT
     *
     * @return the value of MERCHANT_INVOICE.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.AMOUNT
     *
     * @param amount the value for MERCHANT_INVOICE.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT_INVOICE.CREATE_TIME
     *
     * @return the value of MERCHANT_INVOICE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT_INVOICE.CREATE_TIME
     *
     * @param createTime the value for MERCHANT_INVOICE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}