package com.changyi.fi.model;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.MER_ID
     *
     * @mbggenerated
     */
    private Integer MER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.NAME
     *
     * @mbggenerated
     */
    private String NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.TYPE
     *
     * @mbggenerated
     */
    private Short TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.ADDRESS
     *
     * @mbggenerated
     */
    private String ADDRESS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.EMAIL
     *
     * @mbggenerated
     */
    private String EMAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.PHONE1
     *
     * @mbggenerated
     */
    private String PHONE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.PHONE2
     *
     * @mbggenerated
     */
    private String PHONE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.LONGITUDE
     *
     * @mbggenerated
     */
    private BigDecimal LONGITUDE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.LETITUDE
     *
     * @mbggenerated
     */
    private BigDecimal LETITUDE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.ZIP_CODE
     *
     * @mbggenerated
     */
    private String ZIP_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.STATUS
     *
     * @mbggenerated
     */
    private Short STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date CREATE_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.CREATE_BY
     *
     * @mbggenerated
     */
    private String CREATE_BY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date MODIFY_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.MODIFY_BY
     *
     * @mbggenerated
     */
    private String MODIFY_BY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MERCHANT.EXPIRE_TIME
     *
     * @mbggenerated
     */
    private Date EXPIRE_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.ID
     *
     * @return the value of MERCHANT.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.ID
     *
     * @param ID the value for MERCHANT.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.MER_ID
     *
     * @return the value of MERCHANT.MER_ID
     *
     * @mbggenerated
     */
    public Integer getMER_ID() {
        return MER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.MER_ID
     *
     * @param MER_ID the value for MERCHANT.MER_ID
     *
     * @mbggenerated
     */
    public void setMER_ID(Integer MER_ID) {
        this.MER_ID = MER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.NAME
     *
     * @return the value of MERCHANT.NAME
     *
     * @mbggenerated
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.NAME
     *
     * @param NAME the value for MERCHANT.NAME
     *
     * @mbggenerated
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.TYPE
     *
     * @return the value of MERCHANT.TYPE
     *
     * @mbggenerated
     */
    public Short getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.TYPE
     *
     * @param TYPE the value for MERCHANT.TYPE
     *
     * @mbggenerated
     */
    public void setTYPE(Short TYPE) {
        this.TYPE = TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.ADDRESS
     *
     * @return the value of MERCHANT.ADDRESS
     *
     * @mbggenerated
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.ADDRESS
     *
     * @param ADDRESS the value for MERCHANT.ADDRESS
     *
     * @mbggenerated
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.EMAIL
     *
     * @return the value of MERCHANT.EMAIL
     *
     * @mbggenerated
     */
    public String getEMAIL() {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.EMAIL
     *
     * @param EMAIL the value for MERCHANT.EMAIL
     *
     * @mbggenerated
     */
    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL == null ? null : EMAIL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.PHONE1
     *
     * @return the value of MERCHANT.PHONE1
     *
     * @mbggenerated
     */
    public String getPHONE1() {
        return PHONE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.PHONE1
     *
     * @param PHONE1 the value for MERCHANT.PHONE1
     *
     * @mbggenerated
     */
    public void setPHONE1(String PHONE1) {
        this.PHONE1 = PHONE1 == null ? null : PHONE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.PHONE2
     *
     * @return the value of MERCHANT.PHONE2
     *
     * @mbggenerated
     */
    public String getPHONE2() {
        return PHONE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.PHONE2
     *
     * @param PHONE2 the value for MERCHANT.PHONE2
     *
     * @mbggenerated
     */
    public void setPHONE2(String PHONE2) {
        this.PHONE2 = PHONE2 == null ? null : PHONE2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.LONGITUDE
     *
     * @return the value of MERCHANT.LONGITUDE
     *
     * @mbggenerated
     */
    public BigDecimal getLONGITUDE() {
        return LONGITUDE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.LONGITUDE
     *
     * @param LONGITUDE the value for MERCHANT.LONGITUDE
     *
     * @mbggenerated
     */
    public void setLONGITUDE(BigDecimal LONGITUDE) {
        this.LONGITUDE = LONGITUDE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.LETITUDE
     *
     * @return the value of MERCHANT.LETITUDE
     *
     * @mbggenerated
     */
    public BigDecimal getLETITUDE() {
        return LETITUDE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.LETITUDE
     *
     * @param LETITUDE the value for MERCHANT.LETITUDE
     *
     * @mbggenerated
     */
    public void setLETITUDE(BigDecimal LETITUDE) {
        this.LETITUDE = LETITUDE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.ZIP_CODE
     *
     * @return the value of MERCHANT.ZIP_CODE
     *
     * @mbggenerated
     */
    public String getZIP_CODE() {
        return ZIP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.ZIP_CODE
     *
     * @param ZIP_CODE the value for MERCHANT.ZIP_CODE
     *
     * @mbggenerated
     */
    public void setZIP_CODE(String ZIP_CODE) {
        this.ZIP_CODE = ZIP_CODE == null ? null : ZIP_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.STATUS
     *
     * @return the value of MERCHANT.STATUS
     *
     * @mbggenerated
     */
    public Short getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.STATUS
     *
     * @param STATUS the value for MERCHANT.STATUS
     *
     * @mbggenerated
     */
    public void setSTATUS(Short STATUS) {
        this.STATUS = STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.CREATE_TIME
     *
     * @return the value of MERCHANT.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.CREATE_TIME
     *
     * @param CREATE_TIME the value for MERCHANT.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.CREATE_BY
     *
     * @return the value of MERCHANT.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCREATE_BY() {
        return CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.CREATE_BY
     *
     * @param CREATE_BY the value for MERCHANT.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCREATE_BY(String CREATE_BY) {
        this.CREATE_BY = CREATE_BY == null ? null : CREATE_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.MODIFY_TIME
     *
     * @return the value of MERCHANT.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Date getMODIFY_TIME() {
        return MODIFY_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.MODIFY_TIME
     *
     * @param MODIFY_TIME the value for MERCHANT.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setMODIFY_TIME(Date MODIFY_TIME) {
        this.MODIFY_TIME = MODIFY_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.MODIFY_BY
     *
     * @return the value of MERCHANT.MODIFY_BY
     *
     * @mbggenerated
     */
    public String getMODIFY_BY() {
        return MODIFY_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.MODIFY_BY
     *
     * @param MODIFY_BY the value for MERCHANT.MODIFY_BY
     *
     * @mbggenerated
     */
    public void setMODIFY_BY(String MODIFY_BY) {
        this.MODIFY_BY = MODIFY_BY == null ? null : MODIFY_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MERCHANT.EXPIRE_TIME
     *
     * @return the value of MERCHANT.EXPIRE_TIME
     *
     * @mbggenerated
     */
    public Date getEXPIRE_TIME() {
        return EXPIRE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MERCHANT.EXPIRE_TIME
     *
     * @param EXPIRE_TIME the value for MERCHANT.EXPIRE_TIME
     *
     * @mbggenerated
     */
    public void setEXPIRE_TIME(Date EXPIRE_TIME) {
        this.EXPIRE_TIME = EXPIRE_TIME;
    }
}