package com.changyi.fi.model;

import java.util.Date;

public class SysAccessPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access.port
     *
     * @mbggenerated
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_access.access_time
     *
     * @mbggenerated
     */
    private Date accessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access.id
     *
     * @return the value of sys_access.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access.id
     *
     * @param id the value for sys_access.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access.ip
     *
     * @return the value of sys_access.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access.ip
     *
     * @param ip the value for sys_access.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access.port
     *
     * @return the value of sys_access.port
     *
     * @mbggenerated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access.port
     *
     * @param port the value for sys_access.port
     *
     * @mbggenerated
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access.url
     *
     * @return the value of sys_access.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access.url
     *
     * @param url the value for sys_access.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access.access_time
     *
     * @return the value of sys_access.access_time
     *
     * @mbggenerated
     */
    public Date getAccessTime() {
        return accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access.access_time
     *
     * @param accessTime the value for sys_access.access_time
     *
     * @mbggenerated
     */
    public void setAccessTime(Date accessTime) {
        this.accessTime = accessTime;
    }
}