package com.changyi.fi.model;

public class SysServImplPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_serv_impl.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_serv_impl.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_serv_impl.impl_clz
     *
     * @mbggenerated
     */
    private String implClz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_serv_impl.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_serv_impl.id
     *
     * @return the value of sys_serv_impl.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_serv_impl.id
     *
     * @param id the value for sys_serv_impl.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_serv_impl.type
     *
     * @return the value of sys_serv_impl.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_serv_impl.type
     *
     * @param type the value for sys_serv_impl.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_serv_impl.impl_clz
     *
     * @return the value of sys_serv_impl.impl_clz
     *
     * @mbggenerated
     */
    public String getImplClz() {
        return implClz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_serv_impl.impl_clz
     *
     * @param implClz the value for sys_serv_impl.impl_clz
     *
     * @mbggenerated
     */
    public void setImplClz(String implClz) {
        this.implClz = implClz == null ? null : implClz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_serv_impl.weight
     *
     * @return the value of sys_serv_impl.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_serv_impl.weight
     *
     * @param weight the value for sys_serv_impl.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}