package com.changyi.fi.model;

import java.util.Date;

public class VInvoicePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.OPEN_ID
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.TYPE
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.CREDIT_CODE
     *
     * @mbggenerated
     */
    private String creditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.IS_DEFAULT
     *
     * @mbggenerated
     */
    private Short isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.CORP_NAME
     *
     * @mbggenerated
     */
    private String corpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.BANK
     *
     * @mbggenerated
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_invoice.BANK_ACCT
     *
     * @mbggenerated
     */
    private String bankAcct;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.ID
     *
     * @return the value of v_invoice.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.ID
     *
     * @param id the value for v_invoice.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.OPEN_ID
     *
     * @return the value of v_invoice.OPEN_ID
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.OPEN_ID
     *
     * @param openId the value for v_invoice.OPEN_ID
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.TYPE
     *
     * @return the value of v_invoice.TYPE
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.TYPE
     *
     * @param type the value for v_invoice.TYPE
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.USER_NAME
     *
     * @return the value of v_invoice.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.USER_NAME
     *
     * @param userName the value for v_invoice.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.CREDIT_CODE
     *
     * @return the value of v_invoice.CREDIT_CODE
     *
     * @mbggenerated
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.CREDIT_CODE
     *
     * @param creditCode the value for v_invoice.CREDIT_CODE
     *
     * @mbggenerated
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.CREATE_TIME
     *
     * @return the value of v_invoice.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.CREATE_TIME
     *
     * @param createTime the value for v_invoice.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.MODIFY_TIME
     *
     * @return the value of v_invoice.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.MODIFY_TIME
     *
     * @param modifyTime the value for v_invoice.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.IS_DEFAULT
     *
     * @return the value of v_invoice.IS_DEFAULT
     *
     * @mbggenerated
     */
    public Short getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.IS_DEFAULT
     *
     * @param isDefault the value for v_invoice.IS_DEFAULT
     *
     * @mbggenerated
     */
    public void setIsDefault(Short isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.CORP_NAME
     *
     * @return the value of v_invoice.CORP_NAME
     *
     * @mbggenerated
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.CORP_NAME
     *
     * @param corpName the value for v_invoice.CORP_NAME
     *
     * @mbggenerated
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.ADDRESS
     *
     * @return the value of v_invoice.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.ADDRESS
     *
     * @param address the value for v_invoice.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.PHONE
     *
     * @return the value of v_invoice.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.PHONE
     *
     * @param phone the value for v_invoice.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.BANK
     *
     * @return the value of v_invoice.BANK
     *
     * @mbggenerated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.BANK
     *
     * @param bank the value for v_invoice.BANK
     *
     * @mbggenerated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_invoice.BANK_ACCT
     *
     * @return the value of v_invoice.BANK_ACCT
     *
     * @mbggenerated
     */
    public String getBankAcct() {
        return bankAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_invoice.BANK_ACCT
     *
     * @param bankAcct the value for v_invoice.BANK_ACCT
     *
     * @mbggenerated
     */
    public void setBankAcct(String bankAcct) {
        this.bankAcct = bankAcct == null ? null : bankAcct.trim();
    }
}